# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161021_0725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('agenda', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='speaker',
            unique_together=set([('agenda', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('agenda', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set([('agenda', 'name')]),
        ),
    ]
