# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161001_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.Profile'),
            preserve_default=False,
        ),
    ]
