# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20161024_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='duration',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
