# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20161026_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
