# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20161007_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='date',
            new_name='start_at',
        ),
    ]
