# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_agenda_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='profile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
