# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_session_is_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='is_dirty',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
