# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_session_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('start_at',)},
        ),
    ]
