# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Venue'),
        ),
    ]
