# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_session_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Track'),
        ),
        migrations.AlterField(
            model_name='session',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Venue'),
        ),
    ]
