# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20161103_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
