# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20161015_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Track'),
        ),
    ]
