# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 14:52
from __future__ import unicode_literals

import backend.models.profile
from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20161015_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_expiry',
            field=models.DateTimeField(default=backend.models.profile.token_expiry),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=50),
        ),
    ]
