# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20161104_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_sms_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='viewer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
