# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 18:35
from __future__ import unicode_literals

import backend.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20161016_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(max_length=50),
        ),
    ]
