# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20161105_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
