# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20161108_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
