# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20161016_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
