# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20161108_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', null=True),
            preserve_default=False,
        ),
    ]
