# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 14:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_agenda_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'The duration of the event must be at least one day long')]),
        ),
    ]
