# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 16:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20161017_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Duration must be larger than zero'), django.core.validators.MinValueValidator(1440, 'A session cannot be longer than 24 hours long')]),
        ),
    ]
