# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:47
from __future__ import unicode_literals

from django.db import migrations


def gen_slug(apps, schema_editor):
    Agenda = apps.get_model('backend', 'Agenda')
    for agenda in Agenda.objects.all():
        agenda._meta.get_field('slug')._unique = True
        agenda._meta.get_field('slug').pre_save(agenda, True)
        agenda.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_agenda_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop)
    ]
