# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:47
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_populate_agenda_slug_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='agenda', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
