# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_agenda_slug_null'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewer',
            unique_together=set([]),
        ),
    ]
