# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 07:05
from __future__ import unicode_literals

import backend.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20161017_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='last_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(default=backend.helper.UniqueTokenGenerator('Profile', field='verification_token', length=20), max_length=50),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='token',
            field=models.CharField(default=backend.helper.UniqueTokenGenerator('Viewer', field='token', length=20), max_length=30, unique=True),
        ),
    ]
