# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20161018_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
